---
- hosts: all
  become: yes

  handlers:
    - name: restart postgresql
      service: name=postgresql@15-main.service state=restarted

  tasks:
  - name : add signing key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc

  - name : add repository
    apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
      state: present
      filename: pgdg

  - name: install postgresql
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - postgresql-15
      - postgresql-client-15
      - libpq-dev
      - python3-psycopg2

  